services:
  db:
    image: postgres:16
    container_name: postgres_inventario
    environment:
      POSTGRES_DB: inventario_django
      POSTGRES_USER: dantas
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: